In [3]:
####Step1  根据excel参数表自动下载对应公司/季度的偿付能力季度报告

%run CROSS_II_function.ipynb

start_time = time.time()

from datetime import datetime
import pandas as pd

df = pd.read_excel(r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\CROSS_II_config_2025Q4.xlsx', sheet_name='config')

for index, row in df.iterrows():
    company = row['公司']
    quarter = row['季度']
    url = row['网址']
    file_path = row['保存地址']
    file_name = row['保存文件名']
    text_to_find = row['text_to_find']
    xpath = row['xpath']
    control = row['control']
    if control=='Y':
        print(company + quarter)
        try:
            pdf_url = get_download_url(url, text_to_find, xpath)
        except Exception as e:
            print(f"{company} {quarter}：获取下载链接失败：{e}")
            df.at[index, 'download_status'] = '无法获取下载链接'
            continue
        df.at[index, 'pdf_url'] = pdf_url
        df.at[index, 'operation_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        try:
            print(company + quarter)
            if download_pdf(pdf_url, file_path, file_name):
                df.at[index, 'download_status'] = '下载成功'
            else:
                df.at[index, 'download_status'] = '下载失败'
            df.at[index, 'download_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        except Exception as e:
            print(f"{company} {quarter}：下载出错，错误信息：{e}")
            df.at[index, 'download_status'] = f'失败: {e}'
            df.at[index, 'download_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


df.to_excel(r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\CROSS_II_log_2025Q4.xlsx', sheet_name='log', index=False)

# 记录结束时间
end_time = time.time()

# 计算并打印运行时间
elapsed_time = end_time - start_time
print(f"代码运行时间：{elapsed_time}秒")

Requirement already satisfied: webdriver-manager in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.0.2)
Requirement already satisfied: requests in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from webdriver-manager) (2.32.3)
Requirement already satisfied: python-dotenv in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from webdriver-manager) (1.0.1)
Requirement already satisfied: packaging in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from webdriver-manager) (24.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->webdriver-manager) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->webdriver-manager) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->webdriver-manager) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->webdriver-manager) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pip in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.
平安寿险2025Q4
None
Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Found parent a element: https://cdn.life.pingan.com/ilifecore/common/202603301024hmes8bp9alcb.pdf
https://cdn.life.pingan.com/ilifecore/common/202603301024hmes8bp9alcb.pdf
平安寿险2025Q4
PDF downloaded successfully using requests.
Direct download successful.
中国人寿2025Q4
https://www.e-chinalife.com/c/2026-03-26/2ecbf879-1e08-401c-b8d8-6e9625690b45.shtml
https://www.e-chinalife.com/c/2026-03-26/2ecbf879-1e08-401c-b8d8-6e9625690b45.shtml
中国人寿2025Q4
Attempting to download with Selenium.
新华保险2025Q4
None
Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年第四季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Found parent a element: https://static-cdn.newchinalife.com/ncl/pdf/20260327/01f3a9c0-d8fd-4a81-9ac2-69294f278937.pdf
https://static-cdn.newchinalife.com/ncl/pdf/20260327/01f3a9c0-d8fd-4a81-9ac2-69294f278937.pdf
新华保险2025Q4
PDF downloaded successfully using requests.
Direct download successful.
太保寿险2025Q4
None
None
Type2: 没有找到包含特定文本元素的父类a元素，错误：Message: invalid selector: The result of the xpath expression ".." is: [object HTMLDocument]. It should be an element.
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d1280e5e]
	msedgedriver!(No symbol) [0x7ff7d1283295]
	msedgedriver!(No symbol) [0x7ff7d128335f]
	msedgedriver!(No symbol) [0x7ff7d12c32d1]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d12ba4bc]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ba36d]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type3: 没有找到包含特定文本的href链接，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type4: 没有找到该xpath地址，错误：Message: invalid argument: missing command parameters
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12e0492]
	msedgedriver!(No symbol) [0x7ff7d12dff8c]
	msedgedriver!(No symbol) [0x7ff7d1252e85]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!(No symbol) [0x7ff7d125182a]
	msedgedriver!GetHandleVerifier [0x7ff7d16db908+19a038]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

太保寿险2025Q4
太保寿险 2025Q4：下载出错，错误信息：Invalid URL 'not found': No scheme supplied. Perhaps you meant https://not found?
招商信诺2025Q4
https://www.cignacmb.com/Healthbenefits/viewPDF/?url=/sc/doc/xiazai/biangeng/changfunengli20260130.pdf
https://www.cignacmb.com/Healthbenefits/viewPDF/?url=/sc/doc/xiazai/biangeng/changfunengli20260130.pdf
招商信诺2025Q4
Attempting to download with Selenium.
泰康人寿2025Q4
https://www.taikanglife.com/uploader/informationFile/2026/01/30/08005760-f3b0-4a47-8094-7e2a7cd37440.pdf
https://www.taikanglife.com/uploader/informationFile/2026/01/30/08005760-f3b0-4a47-8094-7e2a7cd37440.pdf
泰康人寿2025Q4
PDF downloaded successfully using requests.
Direct download successful.
人保寿险2025Q4
https://www.picclife.cn/picclifewebsite/webfile/cfnljdbgzy/2026-03-26/ff8080819cae92e9019d2964901f016d.html
https://www.picclife.cn/picclifewebsite/webfile/cfnljdbgzy/2026-03-26/ff8080819cae92e9019d2964901f016d.html
人保寿险2025Q4
Attempting to download with Selenium.
没有找到id = download的元素，错误：Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="download"]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

没有找到包含'点击下载'的按钮，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '点击下载')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

没有找到包含'点击下载'的按钮，错误：Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="save"]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

无法找到下载按钮
中邮人寿2025Q4
None
Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Found parent a element: https://www.chinapost-life.com/publish/publish4/publish4_4/202601/P020260128372475186274.pdf
https://www.chinapost-life.com/publish/publish4/publish4_4/202601/P020260128372475186274.pdf
中邮人寿2025Q4
PDF downloaded successfully using requests.
Direct download successful.
工银安盛2025Q4
None
Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年第四季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Found parent a element: https://www.icbc-axa.com/attachmentDir/file/202601/30155902nps5.pdf
https://www.icbc-axa.com/attachmentDir/file/202601/30155902nps5.pdf
工银安盛2025Q4
PDF downloaded successfully using requests.
Direct download successful.
国华人寿2025Q4
Type1: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type2: 没有找到包含特定文本元素的父类a元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年4季度')]"}

There was an error managing msedgedriver (error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_147_WINDOWS)); using driver found in the cache

人保养老 2025Q4：获取下载链接失败：Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 136
Current browser version is 147.0.3912.60 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
	GetHandleVerifier [0x00007FF62BD9F885+25029]
	(No symbol) [0x00007FF62BCF4890]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF62BFFA98A+1947706]
	(No symbol) [0x00007FF62BAFA04E]
	(No symbol) [0x00007FF62BAF9408]
	(No symbol) [0x00007FF62BAF35E5]
	(No symbol) [0x00007FF62BAF03B3]
	(No symbol) [0x00007FF62BB352CD]
	(No symbol) [0x00007FF62BB343CB]
	(No symbol) [0x00007FF62BB28DF3]
	(No symbol) [0x00007FF62BAFD6A6]
	(No symbol) [0x00007FF62BAFCBB3]
	(No symbol) [0x00007FF62BAFD4D3]
	(No symbol) [0x00007FF62BC05F0D]
	(No symbol) [0x00007FF62BC13AAF]
	(No symbol) [0x00007FF62BC0C49F]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF62BE6493A+284650]
	(No symbol) [0x00007FF62BD02221]
	(No symbol) [0x00007FF62BCFACC4]
	(No symbol) [0x00007FF62BCFAE13]
	(No symbol) [0x00007FF62BCECA56]
	BaseThreadInitThunk [0x00007FFA16EAE8D7+23]
	RtlUserThreadStart [0x00007FFA1916C3FC+44]

瑞华健康2025Q4
Type1: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type2: 没有找到包含特定文本元素的父类a元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type3: 没有找到包含特定文本的href链接，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, '2025年第4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type4: 没有找到该xpath地址，错误：Message: invalid argument: missing command parameters
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12e0492]
	msedgedriver!(No symbol) [0x7ff7d12dff8c]
	msedgedriver!(No symbol) [0x7ff7d1252e85]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!(No symbol) [0x7ff7d125182a]
	msedgedriver!GetHandleVerifier [0x7ff7d16db908+19a038]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

处理瑞华健康时出错：Message:
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

瑞华健康2025Q4
瑞华健康 2025Q4：下载出错，错误信息：Invalid URL 'not found': No scheme supplied. Perhaps you meant https://not found?
恒安标准养老2025Q4
https://www.haslpension.com/uiFramework/commonResource/zip/zip/zip/pdfjs-1/web/viewer.html?file=/henganyanglao/attachDir/2026/01/2026012717482594883.pdf
https://www.haslpension.com/uiFramework/commonResource/zip/zip/zip/pdfjs-1/web/viewer.html?file=/henganyanglao/attachDir/2026/01/2026012717482594883.pdf
恒安标准养老2025Q4
弘康人寿2025Q4
Type1: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type2: 没有找到包含特定文本元素的父类a元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type3: 没有找到包含特定文本的href链接，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, '2025年4季度')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type4: 没有找到该xpath地址，错误：Message: invalid argument: missing command parameters
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12e0492]
	msedgedriver!(No symbol) [0x7ff7d12dff8c]
	msedgedriver!(No symbol) [0x7ff7d1252e85]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!(No symbol) [0x7ff7d125182a]
	msedgedriver!GetHandleVerifier [0x7ff7d16db908+19a038]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

http://www.hongkang-life.com/seerkey-iif-web-portal-1.0.0/disclosure/filecatalog/queryPDF?id=2017163074675142657
弘康人寿2025Q4
PDF downloaded successfully using requests.
Direct download successful.
德华安顾2025Q4
Type1: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年第4季度偿付能力')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type1.5: 没有找到包含特定文本的元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(), '2025年第4季度偿付能力')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type2: 没有找到包含特定文本元素的父类a元素，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), '2025年第4季度偿付能力')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]
	msedgedriver!(No symbol) [0x7ff7d12c37d8]
	msedgedriver!(No symbol) [0x7ff7d12c3a75]
	msedgedriver!(No symbol) [0x7ff7d1301927]
	msedgedriver!(No symbol) [0x7ff7d12ba467]
	msedgedriver!(No symbol) [0x7ff7d12ff682]
	msedgedriver!(No symbol) [0x7ff7d12b9cac]
	msedgedriver!(No symbol) [0x7ff7d12b8f06]
	msedgedriver!(No symbol) [0x7ff7d12b9ad3]
	msedgedriver!(No symbol) [0x7ff7d1387569]
	msedgedriver!(No symbol) [0x7ff7d1383d33]
	msedgedriver!(No symbol) [0x7ff7d1392f7c]
	msedgedriver!GetHandleVerifier [0x7ff7d156bcf8+2a428]
	msedgedriver!GetHandleVerifier [0x7ff7d1574b06+33236]
	msedgedriver!GetHandleVerifier [0x7ff7d1556d14+15444]
	msedgedriver!GetHandleVerifier [0x7ff7d1556e59+15589]
	msedgedriver!GetHandleVerifier [0x7ff7d1543d53+2483]
	KERNEL32!BaseThreadInitThunk [0x7ffa16eae8d7+17]
	ntdll!RtlUserThreadStart [0x7ffa1916c3fc+2c]

Type3: 没有找到包含特定文本的href链接，错误：Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, '2025年第4季度偿付能力')]"}
  (Session info: MicrosoftEdge=147.0.3912.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	msedgedriver!GetHandleVerifier [0x7ff7d154f725+de55]
	msedgedriver!GetHandleVerifier [0x7ff7d154f784+deb4]
	msedgedriver!GetHandleVerifier [0x7ff7d18d453a+392c6a]

In [9]:
df[df['download_status'].notna()]

,control,公司,类型,网址,进度,备注,text_to_find,xpath,季度,Y,Q,保存地址,保存文件名,pdf_url,operation_time,download_status,download_time
0,Y,平安寿险,寿险,https://life.pingan.com/gongkaixinxipilu/chang...,成功,NaN,2024年第4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,平安寿险2024Q4偿付能力季度报告摘要.pdf,not found,2025-03-18 16:13:17,失败: Invalid URL 'not found': No scheme supplie...,2025-03-18 16:13:17
1,Y,中国人寿,寿险,https://www.e-chinalife.com/tzzgx/tzzgx/dqbg/c...,成功,NaN,2024年4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,中国人寿2024Q4偿付能力季度报告摘要.pdf,not found,2025-03-18 16:13:30,失败: Invalid URL 'not found': No scheme supplie...,2025-03-18 16:13:30
2,Y,新华保险,寿险,https://www.newchinalife.com/info/53474,成功,NaN,2024年第四季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,新华保险2024Q4偿付能力季度报告摘要.pdf,not found,2025-03-18 16:13:54,失败: Invalid URL 'not found': No scheme supplie...,2025-03-18 16:13:54
3,Y,太保寿险,寿险,https://life.cpic.com.cn/xrsbx/gkxxpl/cfnlxxzq...,成功,NaN,2024年第4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,太保寿险2024Q4偿付能力季度报告摘要.pdf,not found,2025-03-18 16:14:08,失败: Invalid URL 'not found': No scheme supplie...,2025-03-18 16:14:08
4,Y,招商信诺,寿险,https://www.cignacmb.com/xinxi/jibenxinxi/chan...,成功,NaN,2024年第4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,招商信诺2024Q4偿付能力季度报告摘要.pdf,https://www.cignacmb.com/Healthbenefits/viewPD...,2025-03-18 16:14:21,失败: [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\文档\\...,2025-03-18 16:14:35
5,Y,泰康人寿,寿险,https://www.taikanglife.com/publicinfonew/spec...,成功,NaN,2024年第4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,泰康人寿2024Q4偿付能力季度报告摘要.pdf,https://www.taikanglife.com/uploader/informati...,2025-03-18 16:14:50,成功,2025-03-18 16:14:51
6,Y,人保寿险,寿险,https://www.picclife.cn/picclifewebsite/webfil...,成功,NaN,2024年第4季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,人保寿险2024Q4偿付能力季度报告摘要.pdf,not found,2025-03-18 16:15:05,失败: Invalid URL 'not found': No scheme supplie...,2025-03-18 16:15:05
8,Y,工银安盛,寿险,https://www.icbc-axa.com/public/special_infor_...,成功,NaN,2024年第四季度,NaN,2024Q4,2024,4,D:\文档\_工作相关\KPMG\CROSS II\2024Q4,工银安盛2024Q4偿付能力季度报告摘要.pdf,https://www.icbc-axa.com/attachmentDir/file/20...,2025-03-18 16:15:19,成功,2025-03-18 16:15:20

In [11]:
import pandas as pd
import os
import glob
import camelot
%run CROSS_II_function.ipynb
# 假设 extract_tables_from_pdf 和 get_company_params 函数已定义
# from CROSS_II_function import extract_tables_from_pdf, get_company_params, offset

def process_pdf(pdf_file, company_name, fields, df_result, col_offset):
    print(company_name)
    
    keywords = [
    ['偿付能力', '寿险业务保险风险', '控制风险最低资本', '保险合同负债', '保单未来盈余'],
    ['认可资产', '认可负债', '实际资本']
    ]
    
    try:
        # 中邮的表格全有分隔线，使用pdfplumber抽表
        if company_name in ['中邮人寿','海保人寿','人保健康','华汇人寿']:
            extracted_tables = extract_tables_from_pdf(pdf_file)
        # 其他公司的表格不规则，使用camelot抽表
        else:
            extracted_tables = camelot.read_pdf(
                filepath=pdf_file,
                **get_company_params(company_name)
            )
        
        for field in fields:
            # 如果 df_result 中不存在 company_name 或 field，则初始化为 None
            if company_name not in df_result.index or field not in df_result.columns:
                df_result.at[company_name, field] = '无'
                
            found = False  # 添加一个标志变量
            for table in extracted_tables:
                value = offset(table.df if hasattr(table, 'df') else table, field, 0, col_offset)
        
                if value is None or value == "Index out of range" or value == "":
                    continue  # 如果值无效，跳过当前迭代

                for keyword_group in keywords:
                    if any(keyword in str(table.df.values.flatten()) if hasattr(table, 'df') else 
                           keyword in str(table.values.flatten()) for keyword in keyword_group):
                        if (df_result.at[company_name, field] is None or 
                            df_result.at[company_name, field] == '' or 
                            pd.isna(df_result.at[company_name, field]) or 
                            df_result.at[company_name, field] == '无'):
                            if '\n' in value:  #防止两列合并成一列
                                value = value.split('\n')[0]
                            df_result.at[company_name, field] = value
                            found = True  # 设置标志变量为 True
                            break  # 找到值后退出循环
                            
                if found:  # 如果找到值，退出 table 循环
                    break
                        
                       
    except Exception as e:
        print(f"处理文件 {pdf_file} 时发生错误: {e}")


fields = [
    #（一）主要偿付能力指标
    '综合偿付能力充足率', '核心偿付能力充足率', '综合偿付能力溢额',  '核心偿付能力溢额', 
    '认可资产', '认可负债','实际资本','核心一级资本', '核心二级资本','附属一级资本', '附属二级资本','最低资本',
    
    #（四）主要经营指标
    '保险业务收入','净利润','总资产','净资产', '保险合同负债', 
    
    # 实际资本表
    '计入核心一级资本的保单未来盈余', '计入核心二级资本的保单未来盈余',
    '计入附属一级资本的保单未来盈余', '计入附属二级资本的保单未来盈余',
    
    # 认可负债表
    '独立账户负债',

    # 最低资本
    '量化风险最低资本','量化风险最低资本（未考虑特征系数前）',
    
    '寿险业务保险风险最低资本合计', 
    '寿险业务保险风险-损失发生风险最低资本','寿险业务保险风险-退保风险最低资本',
    '寿险业务保险风险-费用风险最低资本','寿险业务保险风险-风险分散效应',
    
    '非寿险业务保险风险最低资本合计', 
    '非寿险业务保险风险-保费及准备金风险最低资本','非寿险业务保险风险-巨灾风险最低资本','非寿险业务保险风险-风险分散效应',
    
    '市场风险-最低资本合计',
    '市场风险-利率风险最低资本','市场风险-权益价格风险最低资本','市场风险-房地产价格风险最低资本',
    '市场风险-境外固定收益类资产价格风险最低资本','市场风险-境外权益类资产价格风险最低资本','市场风险-汇率风险最低资本','市场风险-风险分散效应',
    
    '信用风险-最低资本合计',
    '信用风险-利差风险最低资本','信用风险-交易对手违约风险最低资本','信用风险-风险分散效应',
    
    '量化风险分散效应', 
    '特定类别保险合同损失吸收效应', '损失吸收调整-不考虑上限','损失吸收效应调整上限','控制风险最低资本',
    
    '附加资本'
    '逆周期附加资本','D-SII附加资本','G-SII附加资本','其他附加资本'  
]

#fields = ['寿险业务保险风险-损失发生风险最低资本']

df_result = pd.DataFrame()

start_time = time.time()

# 指定目录路径
directory_path = r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\报告'

# 使用glob模块获取所有.pdf文件的路径
pdf_files = glob.glob(os.path.join(directory_path, '*.pdf'))

for pdf_file in pdf_files:
    company_name = pdf_file[len(directory_path)+1:pdf_file.rfind("20")]
    if company_name in ['财信人寿']: 
    #if company_name in ['中荷人寿']:
        if company_name in ['泰康养老']:  #泰康养老的格式特殊，先上期再本期
            process_pdf(pdf_file, company_name, fields, df_result, 2)
        else:
            process_pdf(pdf_file, company_name, fields, df_result, 1)
            process_pdf(pdf_file, company_name, fields, df_result, 2)

    

end_time = time.time()

elapsed_time = end_time - start_time
print(f"代码运行时间：{elapsed_time}秒")

# 将结果保存到 Excel 文件中

财信人寿

C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 510.61799999999994, 529.0239999999999, 809.2577904761905)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 80.612, 534.98, 826.3315714285715)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 66.81200000000001, 540.98, 826.308)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 72.81200000000001, 529.1, 826.308)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 78.09200000000001, 534.86, 797.0348965517242)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 429.018, 540.98, 821.5218461538461)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 356.638, 540.98, 801.857411764706)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 409.998, 534.9, 826.4421176470588)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 76.77199999999999, 534.98, 814.2646923076924)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 171.56799999999998, 535.22, 825.9941538461538)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 149.368, 522.86, 758.8816)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 579.408, 528.904, 820.7677183098592)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 77.132, 828.98, 325.7141111111111)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 391.818, 528.95, 802.1413333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 84.69200000000001, 540.98, 814.5097777777778)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 71.49199999999999, 540.9, 826.0514482758621)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 71.37199999999999, 528.98, 825.8031724137932)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 89.488, 528.988, 826.0514482758621)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 108.44800000000001, 528.95, 825.4813333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

处理文件 D:\文档\_工作相关\KPMG\CROSS II\2025Q4\报告\财信人寿2025Q4偿付能力季度报告摘要.pdf 时发生错误: max() iterable argument is empty
财信人寿

C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 510.61799999999994, 529.0239999999999, 809.2577904761905)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 80.612, 534.98, 826.3315714285715)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 66.81200000000001, 540.98, 826.308)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 72.81200000000001, 529.1, 826.308)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 78.09200000000001, 534.86, 797.0348965517242)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 429.018, 540.98, 821.5218461538461)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 356.638, 540.98, 801.857411764706)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 409.998, 534.9, 826.4421176470588)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 76.77199999999999, 534.98, 814.2646923076924)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 171.56799999999998, 535.22, 825.9941538461538)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 149.368, 522.86, 758.8816)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 579.408, 528.904, 820.7677183098592)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 77.132, 828.98, 325.7141111111111)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 391.818, 528.95, 802.1413333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 84.69200000000001, 540.98, 814.5097777777778)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 71.49199999999999, 540.9, 826.0514482758621)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 71.37199999999999, 528.98, 825.8031724137932)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 89.488, 528.988, 826.0514482758621)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (66.584, 108.44800000000001, 528.95, 825.4813333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

处理文件 D:\文档\_工作相关\KPMG\CROSS II\2025Q4\报告\财信人寿2025Q4偿付能力季度报告摘要.pdf 时发生错误: max() iterable argument is empty
代码运行时间：16.571075439453125秒

In [13]:
#获取重大投资和重大融资信息
%run CROSS_II_function.ipynb
start_time = time.time()
# 指定目录路径
directory_path = r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\报告'

# 使用glob模块获取所有.pdf文件的路径
pdf_files = glob.glob(os.path.join(directory_path, '*.pdf'))
keyword = ['重大投资','重大融资']
excel_path = r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\重大融资_2025Q4.xlsx'
write_to_excel(pdf_files, keyword, excel_path)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"代码运行时间：{elapsed_time}秒")

代码运行时间：5.853671073913574秒

In [7]:
df_result.to_excel(r'D:\文档\_工作相关\KPMG\CROSS II\2025Q4\df_result_2025Q4_20260419.xlsx', index=True)

In [12]:
df_result.T

Empty DataFrame
Columns: []
Index: []

In [8]:
#
pip install pandas openpyxl requests selenium beautifulsoup4 camelot-py[cv] webdriver_manager

Requirement already satisfied: pandas in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: requests in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.32.3)
Requirement already satisfied: selenium in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.26.1)
Requirement already satisfied: beautifulsoup4 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.12.3)
Requirement already satisfied: webdriver_manager in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.0.2)
Requirement already satisfied: camelot-py[cv] in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.11.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2024.8.30)
Requirement already satisfied: trio~=0.17 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from selenium) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: typing_extensions~=4.9 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: soupsieve>1.2 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: chardet>=3.0.4 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: click>=6.7 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (8.1.7)
Requirement already satisfied: pdfminer.six>=20200726 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (20231228)
Requirement already satisfied: pypdf>=3.0.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (5.1.0)
Requirement already satisfied: tabulate>=0.8.9 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (0.9.0)
Collecting ghostscript>=0.7 (from camelot-py[cv])
  Downloading ghostscript-0.8.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: opencv-python>=3.4.2.17 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (4.10.0.84)
INFO: pip is looking at multiple versions of camelot-py[cv] to determine which version is compatible with other requirements. This could take a while.
Collecting camelot-py[cv]
  Downloading camelot_py-1.0.9-py3-none-any.whl.metadata (9.8 kB)
Collecting pdfminer-six>=20240706 (from camelot-py[cv])
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting opencv-python-headless>=4.7.0.68 (from camelot-py[cv])
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: pypdfium2>=4 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (4.30.0)
Requirement already satisfied: pillow>=10.4.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from camelot-py[cv]) (10.4.0)
Requirement already satisfied: python-dotenv in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from webdriver_manager) (1.0.1)
Requirement already satisfied: packaging in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from webdriver_manager) (24.2)
Requirement already satisfied: pycparser in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.22)
Requirement already satisfied: colorama in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click>=6.7->camelot-py[cv]) (0.4.6)
Requirement already satisfied: cryptography>=36.0.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (43.0.3)
Requirement already satisfied: six>=1.5 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in C:\Users\Lu Quanlin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Downloading camelot_py-1.0.9-py3-none-any.whl (66 kB)
Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
   ---------------------------------------- 0.0/40.1 MB ? eta -:--:--
    --------------------------------------- 0.5/40.1 MB 4.5 MB/s eta 0:00:09
   ------- -------------------------------- 7.6/40.1 MB 25.8 MB/s eta 0:00:02
   ----------------------------- ---------- 29.4/40.1 MB 60.0 MB/s eta 0:00:01
   ------------------------------- -------- 31.5/40.1 MB 61.6 MB/s eta 0:00:01
   ------------------------------- -------- 31.5/40.1 MB 61.6 MB/s eta 0:00:01
   ------------------------------- -------- 31.5/40.1 MB 61.6 MB/s eta 0:00:01
   ------------------------------- -------- 31.7/40.1 MB 26.3 MB/s eta 0:00:01
   -------------------------------- ------- 32.2/40.1 MB 21.3 MB/s eta 0:00:01
   --------------------------------- ------ 33.6/40.1 MB 19.7 MB/s eta 0:00:01
   ------------------------------------- -- 37.7/40.1 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------  39.8/40.1 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 40.1/40.1 MB 18.1 MB/s  0:00:02
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 6.6/6.6 MB 92.7 MB/s  0:00:00
Installing collected packages: opencv-python-headless, pdfminer-six, camelot-py

   ---------------------------------------- 0/3 [opencv-python-headless]
   ---------------------------------------- 0/3 [opencv-python-headless]
   ---------------------------------------- 0/3 [opencv-python-headless]
   ---------------------------------------- 0/3 [opencv-python-headless]
  Attempting uninstall: pdfminer-six
   ---------------------------------------- 0/3 [opencv-python-headless]
    Found existing installation: pdfminer.six 20231228
   ---------------------------------------- 0/3 [opencv-python-headless]
    Uninstalling pdfminer.six-20231228:
   ---------------------------------------- 0/3 [opencv-python-headless]
      Successfully uninstalled pdfminer.six-20231228
   ---------------------------------------- 0/3 [opencv-python-headless]
   ------------- -------------------------- 1/3 [pdfminer-six]
   ------------- -------------------------- 1/3 [pdfminer-six]
   ------------- -------------------------- 1/3 [pdfminer-six]
   ------------- -------------------------- 1/3 [pdfminer-six]
  Attempting uninstall: camelot-py
   ------------- -------------------------- 1/3 [pdfminer-six]
    Found existing installation: camelot-py 0.11.0
   ------------- -------------------------- 1/3 [pdfminer-six]
    Uninstalling camelot-py-0.11.0:
   ------------- -------------------------- 1/3 [pdfminer-six]
      Successfully uninstalled camelot-py-0.11.0
   ------------- -------------------------- 1/3 [pdfminer-six]
   -------------------------- ------------- 2/3 [camelot-py]
   ---------------------------------------- 3/3 [camelot-py]

Successfully installed camelot-py-1.0.9 opencv-python-headless-4.13.0.92 pdfminer-six-20260107
Note: you may need to restart the kernel to use updated packages.

WARNING: camelot-py 1.0.9 does not provide the extra 'cv'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdfplumber 0.11.4 requires pdfminer.six==20231228, but you have pdfminer-six 20260107 which is incompatible.